### ISSUE TITLE
Raisin Toast should modify status bar

### ISSUE THREAD

**Issue by ZevEisenberg** [Raizlabs/RaisinToast#11]
If the text inside the toast is white, it’s weird for the system status bar to stay black (and vice versa). There should be a way to control the system status bar through RaisinToast. It could perhaps use `+[UIColor rz_contrastForColor:]` to determine whether the status bar should be white or black automatically based on the background color.

**Comment by adamhrz** [comment]
Will be pushed as part of next release

**Comment by adamhrz** [comment]
Addressed in #1.0.4 release
