### ISSUE TITLE
displayErrorWithTitle crashes

### ISSUE THREAD

**Issue by jwombat** [Raizlabs/RaisinToast#13]
Invoking the method with or without the level parameter causes a crash:
2015-02-17 21:41:14.564 app[7596:242067] **\* Terminating app due to uncaught 
exception 'NSInvalidArgumentException', reason: '**\* -[__NSArrayM insertObject:atIndex:]: 
object cannot be nil'

**Comment by armcknight** [comment]
I'm also experiencing this issue. `SIGABRT` on line 229 of `RZMessagingWindow.m`, due to `self.messageViewControllerClass` being `NULL`.

**Comment by armcknight** [comment]
@jwombat @adamhrz Setting the `messageViewControllerClass` property of the `RZMessagingWindow` property on your app delegate before showing the toast resolves the issue. Notice the demo calls `reconfigureMessagingWindowForDemoPurposes:` which does exactly this. If you comment out line 34 in the demo's `RZTViewController`, the crash is reproduced.

**Comment by jwombat** [comment]
OK, traced it through and got a handle on it. Thank you.
