### ISSUE TITLE
`RZMessagingWindow.displayedError` has type `NSError` but returns object of type `RZMessage`

### ISSUE THREAD

**Issue by armcknight** [Raizlabs/RaisinToast#14]
The getter override returns an object from the `errorsToDisplay` mutable array, which is populated with `RZMessage` objects in `showMessageFromError:strength:animated:`. Probably just need to access the `error` property on `RZMessage` and return that instead in the getter override.

**Comment by adamhrz** [comment]
Fixed in #1.0.4 release
