### ISSUE TITLE
Incompatibility with UIAlertView

### ISSUE THREAD

**Issue by adolfo** [Raizlabs/RaisinToast#27]
I'm seeing an issue whenever a `UIAlertView` is presented (separate from a RaisinToast alert).

The app crashes with an infinite recursion on `[RZRootMessagingViewController supportedInterfaceOrientations]`

```
- (NSUInteger)supportedInterfaceOrientations {
    UIViewController *topViewController = [RZRootMessagingViewController topViewController];
    return [topViewController supportedInterfaceOrientations];
}
```

**Comment by adamhrz** [comment]
Fixed in #31
